blogs/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

from .feed import LatestPostFeed
app_name='blogs'
urlpatterns = [
    path('tag/<slug:tag_slug>/',views.post_list,name='post_list'),
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share,name="post_share"),
    path('feed/', LatestPostFeed(), name='feed'),
    path('post-create/', views.Post_Create.as_view(), name='post-create'),
    path('update-task/<int:pk>/',views.Post_Update.as_view(),name='update-task'),
    path('login/',views.login_view,name='login'),
    # path('register/',views.RegisterPage.as_view(),name='register'),
    path('logout/',LogoutView.as_view(next_page='login'),name='logout'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blogs.sitemaps import PostSitemap

sitemaps={
    'posts':PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls'),name='blogs'),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishManage(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=250, choices=STATUS_CHOICES, default='draft')
    
    tags=TaggableManager()
    imagefield=models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url=self.imagefield.url
        except:
            url=''
        return url
    objects=models.Manager()
    published_posts = PublishManage()
    
    class Meta:
        ordering = ('-published',)
    
    
    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=[self.published.year,
                                                self.published.month,
                                                self.published.day,
                                                self.slug])


    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Post,
                        on_delete=models.CASCADE,
                        related_name='comment')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)
    
    class Meta():
        ordering=('created',)
    def __str__(self) -> str:
        return f'Comment by {self.name}'

blogs/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post,Comment
from django.http import request
from django.core.paginator import EmptyPage,Paginator,PageNotAnInteger
from .form import EmailPostForm,CommentForm,LoginForm,RegisterForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.urls import reverse_lazy


def post_list(request,tag_slug=None):
    posts = Post.objects.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Post,slug=tag_slug)
        posts=posts.filter(tag__in=[tag])
    paginator=Paginator(posts,3)
    
    paginator=Paginator(posts,3)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request, 'post/list.html', {'posts': posts,'page':page})

def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post,
                            status='published',
                            published__year=year,
                            published__month=month,
                            published__day=day,
                            slug=slug)
    comments=Comment.objects.filter(active=True)
    # if comments.post==Post.title:
    #     comment=comments
    new_comment=None
    if request.method=='POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form=CommentForm()
    
    post_tags_ids=Post.tags.values_list('id',flat=True)
    similar_posts=Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-published')[:4]
    
    return render(request, 'post/detail.html', {'post': post,
                                                'comment_form':comment_form,
                                                'new_comment':new_comment,
                                                'comments':comments,
                                                'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comment']}"
            send_mail(subject, message, 'Abelmekonn8@gamil.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'post/share.html', {'form': form, 'sent': sent})

class Post_Update(UpdateView):
    model=Post
    fields=['title','body','published'] 
    template_name='pos/post_form.html'

class Post_Create(CreateView):
    model = Post
    fields=['title','body','published','status']
    template_name='pos/post_form.html'
    success_url=reverse_lazy('post_list')
    
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(Post_Create,self).form_valid(form)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(post_list)  
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    
    return render(request, 'post/login.html', {'form': form})

def register_view(request,self):
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            if user==None:
                login(self.request,user)
                return redirect(login_view)
            else:
                form.add_error(None,'Invalid input')
    
    return render(request,'post/register.html',{'form':form})

templates/post/Login.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
    </head>
    <body>
        <div class="header-bar">
            <h1>Login</h1>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="button" type="submit" value="Login">
            </form>
            {% comment %} <p>Don't have an account? <a href="{% url 'register' %}"> Register</a></p> {% endcomment %}
        </div>
        
        <script src="" async defer></script>
    </body>
</html>

templates/post/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}">
    <link rel="stylesheet" href="">
</head>
<body>
    <div class="header-bar">
        {% if request.user.is_authenticated %}
            <div class="logo">
                <h1>Hello {{request.user|title}}</h1>
                <h3>You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
            </div>
            <a href="/logout"><button class="btn btn-primary">Log Out</button></a>
        {% else %}
            <div class="logo">
                <h1><a href="/login">Login</a></h1>
            </div>
        {% endif %}
    </div>
    <a class="btn btn-primary" href="">&#x2b;</a>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
    <p>I have created {% my_blogs %}</p>
    {% comment %} <div>
        <p>
            <a href="{% url "blogs:post_feed" %}">Subscribe to my RSS feed</a>
        </p>
    </div> {% endcomment %}
    <script src="" async defer></script>
</body>
</html>

templates/post/detail.html
{% extends "post/base.html" %}
{% load blog_tags %}
{% block title %}
{{post.title}}
{% endblock  %}
{% block content %}

<h1>{{post.title}}</h1>
<img src="{{ post.imagefield.url }}" alt="Post Image">
<p class="date">
    Published {{ post.Published }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<P>
    <a href="{% url 'blogs:post_share' post_id=post.id %}">
        share this post
    </a>
</P>
{% with comment.count as total_comments %}
<h2>
    {{total_comments}} comment {{total_comments|pluralize}}
</h2>
{% endwith %}
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
</p>
{% empty %}
There is no similar post yet!
{% endfor %}
{% for comment in comments %}

<div class="comment">
    <p class="info">
        Comment {{forloop.counter}} by {{ comment.name }}
        {{ comment.body }}
    </p>
</div>
{% empty %}
<p>There is no comment added</p>
{% endfor %}
{% if new_comment %}
<h2>Your comment has been added</h2>
{% else %}
<div class="card" method="POST">
    {% csrf_token %}
    <span class="title">Leave a Comment</span>
    <form class="form">
        <div class="group">
            {{comment_form.name}}
            <label for="name">Name</label>
        </div>
        <div class="group">
            {{comment_form.email}}
            <label for="email">Email</label>
        </div>
        <div class="group">
            {{comment_form.body}}
            <label for="comment">Comment</label>
        </div>
        <button type="submit" value="Add comment">Submit</button>
    </form>
</div>

{% endif %}
{% endblock  %}

templates/post/list.html
{% extends "post/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock  %}
{% block content %}
<!-- <p class="tags">
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{tag.name}}
        </a>
        {% if not forloop.last %},{% endif %}
    {% endfor %}
</p> -->
{% for post in posts %}
    <div class="card">
        {% if post.imagefield %}
        <div class="card-image">
            <img src="{{ imagefield.url }}" alt="Post Image">
        </div>
        {% endif %}
        <div class="category"> <h2>
            <a href="{{post.get_absolute_url}}">
                {{post.title}}
            </a>
        </h2> </div>
        <div class="heading"> {{ post.body|markdown|truncatewords:30 }}
            <div class="author"> By <span class="name">{{ post.author }}</span> {{ post.published }} </div>
        </div>
        <div class="tags">Tags: {{post.tags.all|join:", "}}</div>
    </div>
{% endfor %}
{% include "post/pagenator.html" with page=posts %}
{% endblock content %}

templates/post/pagenator.html
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
        <a href="?page={{ posts.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>
        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/post/post_form.html
{% extends "post/base.html" %}
{% load blog_tags %}
{% block content %}
<h1>Create Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock  %}

templates/post/share.html
{% extends "post/base.html" %}
{% block title %}Post Share{% endblock  %}
{% block content %}
    {% if sent %}
    <h1>Email sent successfully</h1>
    <p>{{post.title}} successfully sent to {{form.cleaned_data_to}}</p>
    {% else %}
    <h1>Share {{post.title}} by Email</h1>
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
    <!-- {% for field in form %}
        <div>
            {{ field.errors }}
            {{ field.lable_tag }} {{ field }}
        </div>
    {% endfor %}
    <input type="hidden" name="csrfmiddlewaretoken" value="26JjKo2lcEtYkGoV9z4XmJlEHLXN5LDR"/> -->
{% endblock  %}